spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #Normal Config
        - id: keycloak-admin-client
          uri: lb://keycloak-admin-client
          predicates:
            - Path=/api/v1/group/** , /api/v1/user/**
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/v1/task/**

        #Configure Swagger With Gateway
        - id: keycloak-admin-client-swagger
          uri: lb://keycloak-admin-client
          predicates:
            - Path=/v3/api-docs/keycloak-admin-client
          filters:
            - RewritePath=/v3/api-docs/keycloak-admin-client,/v3/api-docs
        - id: task-service-swagger
          uri: lb://task-service
          predicates:
            - Path=/v3/api-docs/task-service
          filters:
            - RewritePath=/v3/api-docs/task-service,/v3/api-docs
server:
  port: 9090
#Swagger UI Config
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
#Register into Eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, circuitbreakers
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0