spring:
  application:
    name: keycloak-admin-client
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master  # Verify JWT tokens from Keycloak realm
keycloak:
  realm: master
  resource: api-gateway
  auth-server-url: http://localhost:8080 #docker container
  credentials:
    client-id: api-gateway
    secret: fRz2vJjIeM69NB06LbcujMWwZxzWYJlG
    provider: secret
# Eureka Configuration
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
# Management and Health
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, circuitbreakers
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    org.keycloak: DEBUG
    org.springframework.web: DEBUG